# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit, pre-push]

repos:
# This one is a tool to debug, it will log it's arguments. Good way to see what
# is being passed to a hook.
# - repo: meta
#   hooks:
#     - id: identity

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
      stages: [pre-commit]
    - id: check-executables-have-shebangs
      stages: [pre-commit]
    - id: check-shebang-scripts-are-executable
      stages: [pre-commit]
    - id: end-of-file-fixer
      stages: [pre-commit]
    - id: check-json
      stages: [pre-commit]
    - id: check-toml
      stages: [pre-commit]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.6
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
      stages: [pre-push]
    # Run the formatter.
    - id: ruff-format
      stages: [pre-commit]

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
    - id: bandit
      pass_filenames: false
      args: ['-r', 'polar_labs/', '-c', '.bandit.yml']
      stages: [pre-push]

# - repo: https://github.com/python-poetry/poetry
#   rev: 1.5.0
#   hooks:
#     - id: poetry-check
#       stages: [pre-push]
#     - id: poetry-lock
#       stages: [pre-push]
