# Generated by Django 5.0.2 on 2024-03-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='blog.blogposttag'),
        ),
    ]
