# Generated by Django 5.0.2 on 2024-03-20 23:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='title-slug', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
