# Generated by Django 5.0.4 on 2024-11-08 02:37

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='blogposttag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='blogposttag',
            name='color',
            field=models.CharField(choices=[('surface-default', 'Surface Default'), ('surface-alt', 'Surface Alt'), ('dark-blue', 'Dark Blue'), ('dark', 'Dark'), ('darker', 'Darker'), ('grey', 'Grey'), ('light-grey', 'Light Grey'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary'), ('white', 'White')], default='primary', max_length=24),
        ),
        migrations.AddField(
            model_name='blogposttag',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name', unique=True),
        ),
    ]
