namespace: ${APP_NAME}-${ENV_NAME}
appName: ${APP_NAME}
replicas: ${POD_REPLICAS}
imageLocation: ${IMAGE_NAME}
registrySecretName: ${REGISTRY_SECRET_NAME}
containerPorts:
  - name: http
    port: 80
    targetPort: 8000
envVars:
  DEBUG: ${DEBUG} # bool
  ALLOWED_HOSTS: "${ALLOWED_HOSTS}" # comma separated list of allowed hosts
  CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS}" # comma separated list of allowed CORS origins with protocol
  CORS_ALLOWED_ORIGIN_REGEXES: "${CORS_ALLOWED_ORIGIN_REGEXES}" # comma separated list of allowed CORS origins with protocol as regexes
  CSRF_COOKIE_DOMAIN: ${CSRF_COOKIE_DOMAIN} # .yourwebsite.com, remove the first . if you don't want to allow subdomains
  CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS} # comma separated list of allowed csrf origins, https://*.example.com for example
  SAVE_STATIC_FILES_CDN: ${SAVE_STATIC_FILES_CDN} # bool

  # Digital Ocean Spaces
  # see django-storages docs for where to get these
  AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME}
  AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
  AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
  AWS_DEFAULT_ACL: ${AWS_DEFAULT_ACL}
  AWS_S3_CUSTOM_DOMAIN: ${AWS_S3_CUSTOM_DOMAIN}

  # deploy vars
  DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
  DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
  ENV_NAME: ${ENV_NAME}
  SENTRY_DSN: ${SENTRY_DSN}
  SENTRY_RELEASE_NAME: ${SENTRY_RELEASE_NAME}
secrets:
  - name: django-secrets
    type: Opaque
    data:
      SECRET_KEY: "${SECRET_KEY}"
      DATABASE_URL: ${DATABASE_URL} # format: psql://user:password@url:port/dbname?param1=value1&...
  - name: aws-creds
    type: Opaque
    data:
      AWS_S3_ACCESS_KEY_ID: "${AWS_S3_ACCESS_KEY_ID}"
      AWS_S3_SECRET_ACCESS_KEY: "${AWS_S3_SECRET_ACCESS_KEY}"
clusterIssuerName: ${CLUSTER_ISSUER}
tlsSecretName: tls-${APP_NAME}-${ENV_NAME}
disableContentSizeChecksNginx: true
hosts:
  - domainName: ${ENV_NAME}-api.${BASE_URL}
    ingressPaths:
      - path: /
        type: Prefix
        servicePort: 80
